### ISSUE TITLE
Some state issues in data entry

### ISSUE THREAD

**Issue by rsbdotph** [jhone18/Payroll#2]
Timesheet entry is currently disabled.
OT Sheet entry is currently disabled.

Earning Entry 
 -"New" button is disabled
 -Recur Start/Recur End when saved with blank value displays "Invalid date"

Deduction Entry 
 -"New" button is disabled
 -Recur Start/Recur End when saved with blank value displays "Invalid date"
 -add validation: recur start >= recur end (if not null)

**Comment by jhone18** [comment]
- "New" button is now enabled upon clicking the Employee
- Recur Start/Recur End displays blank when saved with blank value
- Added validation: recur start >= recur end (if not null) - tooltip on Recur End
