### ISSUE TITLE
previous validation error is showing

### ISSUE THREAD

**Issue by rsbdotph** [jhone18/Payroll#4]
Previous validation error shows even if there is no validation error in current entry.
To replicate issue, 
Open Deduction entry, edit then try to trigger the validation error "recur start should be greater then.." then close popup without saving.
Edit again any row, the validation error is now showing

![errdate2](https://user-images.githubusercontent.com/28914633/29416781-c56bdf3e-8399-11e7-906b-146838e08f0e.jpg)

**Comment by jhone18** [comment]
oks na to. sa wakas nakita ko din.
